# Nvidia Drivers
nvidia_driver_branch: "535"
cuda_version: "12.4"
nvidia_driver_ubuntu_install_from_cuda_repo: true
nvidia_driver_persistence_mode: true
nvidia_driver_dkms: true
nvidia_driver_skip_reboot: false

# Kubernetes
kube_network_plugin: calico
container_manager: containerd

# Docker installation settings for oven nodes
docker_edition: "ce"
docker_package: "docker-ce"
docker_install_compose_plugin: true
docker_users:
  - oven

# NVIDIA Container Toolkit install vars
nvidia_docker_use_nvidia_repo: true
nvidia_docker_skip_reboot: false
nvidia_docker_containerd: false   # Set to true if you're using containerd instead of Docker