- name: Install Docker on oven nodes
  hosts: all
  become: true
  roles:
    - geerlingguy.docker

  post_tasks:
    - name: Check Docker version
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Display Docker version
      debug:
        msg: "Docker installed: {{ docker_version.stdout }}"
